AWSTemplateFormatVersion: '2010-09-09'
Description: S3 static website hosting with a Cloudfront distribution in front 
Parameters:
  DomainNameParameter:
    Type: String
    Description: Name of the domain to use in deployment
  CertificateARNParameter:
    Type: String
    Description: ARN of the certificate to use
  HostedZoneIDParameter:
    Type: String
    Description: <optional> Hosted Zone ID used to store website DNS information. If no Hosted Zone ID is provided, one will be created
    Default: NONE
Outputs:
  WebsiteBucketCRUDPolicyArn:
    Export:
      Name: WebsiteBucketFullAccessPolicyArn
    Value: !GetAtt [ WebsiteBucketFullAccessPolicy, Arn ]
    Description: ARN for policy allowing caller to CRUD objects in the website bucket 

Conditions:
  CreateHostedZone: !Equals [!Ref HostedZoneIDParameter, NONE]

Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      VersioningConfiguration:
        # Enabled, Suspended
        Status: Suspended
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html

  WebsiteBucketCRUDPolicy:
    Type: AWS::IAM::ManagedPolicy
    DependsOn:
      - WebsiteBucket
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Resource: 
              - !GetAtt [ WebsiteBucket, Arn ]
            Action:
              - s3:ListBucket
              - s3:ListBucketVersions
              - s3:ListAllMyBuckets
          - Effect: Allow
            Resource: !Sub
              - ${ARN}/*
              - { ARN: !GetAtt [ WebsiteBucket, Arn ]}

  WebsiteDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn:
      - WebsiteBucket
    Properties:
      DistributionConfig:
        Origins:
          - Id: StaticWebsite
            DomainName: !Sub
              - ${BUCKET}.s3-website-${AWS::Region}.${AWS::URLSuffix}
              - { BUCKET: !Ref WebsiteBucket }
            CustomOriginConfig:
              # Amazon S3 only supports HTTP for communication
              OriginProtocolPolicy: http-only
        Enabled: true
        DefaultRootObject: index.html
        Aliases:
          - !Ref DomainNameParameter
        DefaultCacheBehavior:
          TargetOriginId: StaticWebsite
          ViewerProtocolPolicy: redirect-to-https
          MinTTL: 900
          MaxTTL: 1800
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateARNParameter
          SslSupportMethod: sni-only
        HttpVersion: http2

  WebsiteZone:
    Type: AWS::Route53::HostedZone
    Condition: CreateHostedZone
    Properties:
      Name: !Sub
        - ${DOMAIN}.
        - { DOMAIN: !Ref DomainNameParameter }

  WebsiteDNS:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !If [ CreateHostedZone, !Ref WebsiteZone, !Ref HostedZoneIDParameter ]
      RecordSets:
        - Name: !Ref DomainNameParameter
          Type: A
          AliasTarget:
            DomainName: !GetAtt [ WebsiteDistribution, DomainName ]
            HostedZoneId: Z2FDTNDATAQYW2
    DependsOn:
      - WebsiteZone
      - WebsiteDistribution